language: generic  
sudo: required  
dist: trusty  
env:  
  - CLI_VERSION=latest
addons:  
  apt:
    packages:
    - gettext
    - libunwind8
    - curl
os:  
  - linux
branches:  
  only:
    - master
install:  
- curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?LinkID=809130
- mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet
- ln -s /opt/dotnet/dotnet /usr/local/bin
script:  
  - ./build.sh