init:
  - git config --global core.autocrlf true

build_script:
  - ps: .\build.ps1 -Target "AppVeyor"

# tests are run by build scripts
test: off

cache:
# invalidate cache if build.cake or build packages change
- tools -> build.cake, build/project_build_tools.json
- .dotnet -> build.cake